[2024-07-07T15:25:26.082+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T15:25:26.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dog_api_pipeline.get_don_api manual__2024-07-07T15:25:23.146749+00:00 [queued]>
[2024-07-07T15:25:26.121+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dog_api_pipeline.get_don_api manual__2024-07-07T15:25:23.146749+00:00 [queued]>
[2024-07-07T15:25:26.122+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T15:25:26.135+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_don_api> on 2024-07-07 15:25:23.146749+00:00
[2024-07-07T15:25:26.144+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=154885) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-07T15:25:26.145+0000] {standard_task_runner.py:63} INFO - Started process 154919 to run task
[2024-07-07T15:25:26.144+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dog_api_pipeline', 'get_don_api', 'manual__2024-07-07T15:25:23.146749+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dog_api_pipeline.py', '--cfg-path', '/tmp/tmpwsaaktv2']
[2024-07-07T15:25:26.146+0000] {standard_task_runner.py:91} INFO - Job 63: Subtask get_don_api
[2024-07-07T15:25:26.185+0000] {task_command.py:426} INFO - Running <TaskInstance: dog_api_pipeline.get_don_api manual__2024-07-07T15:25:23.146749+00:00 [running]> on host 64c03b0d339f
[2024-07-07T15:25:26.273+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dog_api_pipeline' AIRFLOW_CTX_TASK_ID='get_don_api' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T15:25:23.146749+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T15:25:23.146749+00:00'
[2024-07-07T15:25:26.275+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T15:25:26.636+0000] {dog_api_pipeline.py:13} INFO - {'status': 'error', 'message': 'No route found for "GET http://dog.ceo/api/breeds/image/random%20Fetch!" with code: 0', 'code': 404}
[2024-07-07T15:25:26.638+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T15:25:26.639+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T15:25:26.647+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dog_api_pipeline, task_id=get_don_api, run_id=manual__2024-07-07T15:25:23.146749+00:00, execution_date=20240707T152523, start_date=20240707T152526, end_date=20240707T152526
[2024-07-07T15:25:26.682+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T15:25:26.695+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T15:25:26.701+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
